### ISSUE TITLE
Allow ascii mode to be activated using -a

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/TheCatAPI-Cli#2]
This should be a relatively easy task for those who know a bit about bash. Just take the code from line 2 of [catpic.sh](https://github.com/JeffResc/TheCatAPI-Cli/blob/master/catpic.sh#L2) and [cat.sh](https://github.com/JeffResc/TheCatAPI-Cli/blob/master/cat.sh#L2), add an "or" logical operator to allow "-a" to be used and update the README to include the new documentation.

**Comment by Trafitto** [comment]
Hi, can I work on this?

**Comment by JeffResc** [comment]
Resolved in PR #4, thank you to @PurpleBooth for their contribution.
